# Generated by Django 4.1.7 on 2023-03-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_student_id_alter_student_mobile_and_more"),
        ("quiz", "0005_auto_20201209_2125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=50, verbose_name="Kurs nomi"),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="question_number",
            field=models.PositiveIntegerField(verbose_name="Savollar soni"),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_marks",
            field=models.PositiveIntegerField(verbose_name="Umumiy BAli"),
        ),
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.course",
                verbose_name="Qaysi_test",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(verbose_name="baholari"),
        ),
        migrations.AlterField(
            model_name="result",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.course",
                verbose_name="Qaysi imtihon",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="marks",
            field=models.PositiveIntegerField(verbose_name="Bahosi"),
        ),
        migrations.AlterField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
                verbose_name="Ismi",
            ),
        ),
    ]
