# Generated by Django 4.1.7 on 2023-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0002_alter_post_options_alter_post_exam_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyfutureForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
