# Generated by Django 4.1.7 on 2023-03-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0004_alter_myfutureform_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursesBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("cost_course", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/")),
                ("teacher", models.CharField(max_length=150)),
            ],
        ),
    ]
