# Generated by Django 4.1.7 on 2023-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0005_coursesbar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myfutureform",
            old_name="phone_number",
            new_name="Telefon_raqamingiz",
        ),
        migrations.RenameField(
            model_name="myfutureform",
            old_name="full_name",
            new_name="ism_familyangiz",
        ),
        migrations.RemoveField(
            model_name="myfutureform",
            name="description",
        ),
        migrations.AddField(
            model_name="myfutureform",
            name="Qaysi_kursga_yozilmoqchisiz",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
