# Generated by Django 4.1.7 on 2023-03-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0006_rename_phone_number_myfutureform_telefon_raqamingiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myfutureform",
            name="Qaysi_kursga_yozilmoqchisiz",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("PreIELTS", "PreIELTS"),
                    ("Matematika", "Matematika"),
                    ("Fizika", "Fizika"),
                    ("bolalar matematikasi", "bolalar matematikasi"),
                    ("Kimyo", "Kimyo"),
                    ("Biologiya", "Biologiya"),
                ],
                default="IELTS",
                max_length=800,
            ),
        ),
        migrations.AlterField(
            model_name="myfutureform",
            name="ism_familyangiz",
            field=models.CharField(max_length=200),
        ),
    ]
