# Generated by Django 4.1.7 on 2023-03-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0007_alter_myfutureform_qaysi_kursga_yozilmoqchisiz_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoursesBar",
            new_name="Courses",
        ),
    ]
