# Generated by Django 4.1.7 on 2023-03-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0008_rename_coursesbar_courses"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="web_member",
        ),
    ]
