# Generated by Django 4.1.7 on 2023-03-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0009_alter_post_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="myfutureform",
            table="MyfutureFormmember",
        ),
    ]
