# Generated by Django 4.1.7 on 2023-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0010_alter_myfutureform_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="students",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="courses",
            name="time",
            field=models.CharField(default="2 soat", max_length=20),
        ),
    ]
