# Generated by Django 4.1.7 on 2023-03-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0011_courses_students_courses_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course_data",
        ),
    ]
