# Generated by Django 4.1.7 on 2023-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enter", "0016_feedbacks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbacks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
