# Generated by Django 3.0.5 on 2023-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=40, verbose_name='Qaysi guruhdan siz'),
        ),
    ]
