# Generated by Django 4.1.7 on 2023-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_auto_20230311_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(max_length=20, verbose_name="Nomeri"),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pic/Student/",
                verbose_name="profil rasmi",
            ),
        ),
    ]
